name: Run abaplint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  abaplint:
    name: abaplint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - name: Run abaplint
        run: |
          npm -g install @abaplint/cli
          abaplint
